### ISSUE TITLE
Square Wave from DS1307 not enabled?

### ISSUE THREAD

**Issue by zoomx** [rparrett/pongclock#2]
It seems that in the sketch there is no code to enable the square wave output from DS1307.

In initclock() I added these

```
  //Enable Square Wave Output
  Wire.beginTransmission(DS1307_I2C_ADDRESS);
  Wire.write(0x07); // move pointer to SQW address
  Wire.write(0x10); // sends 0x10 (hex) 00010000 (binary)
  Wire.endTransmission();
```

and a 
# define DS1307_I2C_ADDRESS 0x68

at the beginning

I made a porting for cheap OLED display here
[https://github.com/zoomx/OLED-Pong-Clock](url)

**Comment by rparrett** [comment]
It looks like newer versions of RTClib actually have support built-in for various square wave output settings, so I've implemented it that way.

I wonder why my DS1307 seems to default to 1hz square wave mode.

If you get a chance, I'd love to see pictures/video of pongclock running on another device!

Thanks!
